### ISSUE TITLE
real time output

### ISSUE THREAD

**Issue by yyong-brs** [apenella/go-ansible#120]
Hello:
When you have time, can you give an example of how to get real-time output from playbook execution instead of waiting until the final steps are executed.

thanks

**Comment by apenella** [comment]
Hi @yyong-brs!
Thank you for opening that question!

Do you mean a real-time output using the JSON stdout callback? In that case, is not possible because the stdout plugin waits until the playbook finishes before giving you a response.

If you use the default executor with the default Ansible stdout callback, the Ansible output is already redirected to the stdout, such as a real-time output.

**Comment by apenella** [comment]
hi @yyong-brs 
I close the issue since it seemed to be clarified by my previous response.
Thanks!

**Comment by prakasa-tkpd** [comment]
Hi, sorry to continue this issue, since I didn't see another issue similar like this and still open. Is there any example code to get Ansible stdout with default executor ?

**Comment by apenella** [comment]
Hi @prakasa-tkpd!
You have available [that](https://github.com/apenella/go-ansible/blob/master/examples/ansibleplaybook-json-stdout/ansibleplaybook-json-stdout.go) example, where you can see how to write the execution's stdout in a buffer.

If you are looking for another kind of example, please open a new issue describing your requirements, and I will be happy to help you :)

**Comment by apenella** [comment]
Hi @prakasa-tkpd @yyong-brs 
The [[v2.2.0 release](https://github.com/apenella/go-ansible/releases/tag/v2.2.0) is now available and includes support for handling real-time JSON output using the `ansible.posix.jsonl` stdout callback method.
