### ISSUE TITLE
when i run job using go-ansible in dockerized environment as microservice it block all traffic to my existing other docker and the system become inaccessible 

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [apenella/go-ansible#153]
is this common ?

**Comment by apenella** [comment]
Hi @MohamedKHALILRouissi!
I am not aware of anyone else experiencing this issue.

`go-ansible` doesn't handle container or networking operations, it just executes Ansible commands. Therefore, I believe the root cause lies elsewhere.

Do you have any clues that suggest this issue is related to `go-ansible`?

**Comment by apenella** [comment]
@MohamedKHALILRouissi, is there any update on this issue? Have you identified the cause of the described behaviour?
Thanks!

**Comment by apenella** [comment]
@MohamedKHALILRouissi  I close the issue due to the lack of activity. If you have any questions, please, feel free open a new issue.
