### ISSUE TITLE
How to kill the process

### ISSUE THREAD

**Issue by kinnylee** [apenella/go-ansible#16]
DefaultExecute Execute function don't save exec.Command object, I can't call cmd.Process.Kill() to kill the ansible-playbook process.

**Comment by apenella** [comment]
Hi @kinnylee 
DefaultExecute does not provide any control over ansible-playbook process then you can't kill it.
I will think how to solve it.
By the way, you could build your own executor, while the default executor does not support it.

Thank you!

**Comment by zhangguanzhang** [comment]
could use this method https://golang.org/pkg/os/exec/#CommandContext

**Comment by apenella** [comment]
Thanks @zhangguanzhang!
I have not started working on this issue but, as you has pointed out, is a good approach to use a context to manage it, and use https://golang.org/pkg/os/exec/#CommandContext sounds good.

I need to think in depth how inject that context. I may create an attribute on `AnsiblePlaybookCmd` for the context but I don't if I want it.
@kinnylee what do you think about to manage the process using a context attribute, does it fit to your needs?

**Comment by zhangguanzhang** [comment]
could use a demo,like this
```
	sigs := make(chan os.Signal)
	ctx, cancel := context.WithCancel(context.Background())
	var cancelOnce sync.Once
	defer cancel()
	go func() {
		for range sigs {
			cancelOnce.Do(func() {
				logrus.Info("Receiving a termination signal, gracefully shutdown!")
				cancel()
			})
			logrus.Info("The goroutines pool has stopped, please wait for the remaining tasks to complete.")
		}
	}()
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
```
and get the ctx to `cmd.CommandContext`, and https://github.com/apenella/go-ansible/blob/master/execute/defaultExecute.go#L107-L111 change to
```
	select {
	case <-execDoneChan:
        case <-ctx.Done():
            log.Warnf("timeout kill job  ppid:%d", cmd.Process.Pid)
            syscall.Kill(cmd.Process.Pid, syscall.SIGKILL)
	case err := <-execErrChan:
		return errors.New("(DefaultExecute::Execute)", "Error managing results output", err)
	}
```
```

**Comment by apenella** [comment]
hi @kinnylee, @zhangguanzhang 
I start working on that issue.

@zhangguanzhang, as you proposed, I used [CommandContext](https://golang.org/pkg/os/exec/#CommandContext) method. I do not control the process state because it is already done by exec package (https://golang.org/src/os/exec/exec.go?s=6768:6841#L451)

Regarding the signals management, I do not want the packaged to have any responsability upon application behavior, then any kind of control such signals or timeouts should done outside the package, from the `Run` caller. I have written a couple of examples `signals-and-cancellation-ansibleplaybook` and `timeout-ansibleplaybook` still placed on the working branch.

**Comment by apenella** [comment]
@kinnylee  @zhangguanzhang v1.0.0 published. There you could pass a context to manage d'execution flow.
