### ISSUE TITLE
Any plans to add rest interface

### ISSUE THREAD

**Issue by deveshk0** [apenella/go-ansible#18]
is there plan to add rest interface to this, so playbooks can be excuted via rest calls

**Comment by apenella** [comment]
Hi @deveshk0 
There is no plans to add a rest interface. I want the package to act as a simple ansible-playbook interface for go.
I see a rest interface as an application that runs in front go-ansbile, not a package feature.

I could think to code a rest api to interact to go-ansible in the future, because its sounds good, but I would do as a new project.

I close your issue.

Thanks!

**Comment by apenella** [comment]
hi @deveshk0!
I am working on the following aside project, which is a rest api that enables you to execute Ansible playbooks.
https://github.com/apenella/ransidble

I am still working on it, however you can start playing with it.
Cheers!
