### ISSUE TITLE
Add Ansible ad-hoc

### ISSUE THREAD

**Issue by clementblaise** [apenella/go-ansible#25]
Hi,

Would it make sense to add the ad hoc module in this repo?

I really like how this repo enable to use playbook with go and I would like to use the mechanism for ad-hoc command. I'm wondering if I should create a new repo or if is something we could add here.

**Comment by apenella** [comment]
Hi @clementblaise 
thanks you very much for ideas!

What you mean is to run ad-hoc modules through `ansible` command, such is described on that link https://docs.ansible.com/ansible/latest/user_guide/intro_adhoc.html, isn't?

It would be really interesting to include other ways to interact with ansible ecosystem such ansible, ansible-galaxy,... 
The package uses `ansible-playbook` command instead of `ansible` and since they are not the same functionality, I would keep them separately. I could work on how to run `ansible` command, which it lets you to use ad-hoc modules.

You are welcome to create a PR :)

**Comment by zhangguanzhang** [comment]
I also need ad-hoc,like this command:
```
ansible all -m ping
```

**Comment by clementblaise** [comment]
PR #29

**Comment by apenella** [comment]
@clementblaise version 1.0.0 already published . you can execute ansible adhoc command using that version

**Comment by clementblaise** [comment]
Thanks you @apenella I will integrate it into my project
