### ISSUE TITLE
missing package measure for 1.1.5

### ISSUE THREAD

**Issue by superops-team** [apenella/go-ansible#97]
go: finding module for package github.com/apenella/go-ansible/pkg/execute/measure

	github.com/apenella/go-ansible/pkg/execute/measure: module github.com/apenella/go-ansible@latest found (v1.1.5), but does not contain package github.com/apenella/go-ansible/pkg/execute/measure

**Comment by apenella** [comment]
HI @superops-team 
measure package is not available on v1.1.5, it is only available on master branch and it does not belong to any release yet.
On [release notes](https://github.com/apenella/go-ansible/blob/master/RELEASE_NOTES.md) you could see those changes that are already implemented but does not belong to any release.
In case that is required any fix, it will be released on v1.1.6, otherwise it will be available on v1.2.0.
Thanks!

**Comment by apenella** [comment]
@superops-team since there is no update on that issue, I am going to close it. Just to let you know the measure package will be released these week on v1.1.6
